>Mesophlebion_trichopodum_Wade4416_KTHU1690_01_r1_1.000_abundance_94
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------cccccaacgagacacctcaattaacctat
ttcaggttgtttggattcacacaacttgtttggaagcaaaatatggaagccacttcaa-t
tttttcctgcctttggtctttccaaaacactttgcaattcagccattcaggcttttaata
tacatgaatggctcaattgagcccccccccccc--ccagacttttttcactggagccaat
attgtatcaaacaggtcgataaaggcgagatcgacggttttactaggctccaaaaaaaat
ggag----------------------------------------------------g
>Meniscium_chrysodioides
aaatgaattttgggcgatgaggcgagataggtacagagactcgatgggggccattccaac
gagcagtttgttagttactagttctcgaaataactgaatatctaattgtcttgcctggtt
aactgcatgggtggggtaagcctagaagtatgagaccgaagcctggtaagaagggaaaat
tttaatctccccccccccttatctcgacgcggacctctcggtttggggccaatattcatc
cgcaaaattacgttcgtacttagcaatgcaacacggggtaaactacttccactattgcta
gtacacatactattcccttacccattgcgggatcccactccattccaataaaaactgttc
aacaagcgagtcggtagcaaaaaatgacactttcgtgaatggaggtagagtcccattcta
tacatttaatgaaatgaaaaatggcggcgcaagttgcagtaggacgaaaatccgttggtt
tcacaggaccgtgagggttcgactccctctatccccaacgagacacttcaaataacctat
ttcaggttgtttggattcacacaacttgttcggaagcaaaatacggaagccacttcaatt
tttttcctgcctttggtctttcaaaaacactttgcaattgagccattcaggcttttcata
tacatgaatggctcaattgagccccccccccccctctagactttatttactggaaccaat
attgtattaaacaggtcgataaaggcgagatcgacggtttgactaggctccaaaaaaatg
gagttgaaaaatatactcaacggattttcagttgagttttatccgtaaatgcattag
