>Mesophlebion_trichopodum_Wade4416_KTHU1690_01_r2_1.000_abundance_112
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------gaagccacttcaa-t
tttttcctgcctttggtctttccaaaacactttgcaattgagccattcaggcttttaata
tacatgaatggctcaattgag-cccccccccccctccagactttattcactggagccaat
attgtatcaaacaggtcgataaaggcgagatcgacggtttgactaggctccaaaaaaaat
ggagttgaaaaatagactcaacggattttcagttgagttttatccgtagatgcattagcc
gagatagctcagtcggt
>Meniscium_chrysodioides
aaatgaattttgggcgatgaggcgagataggtacagagactcgatgggggccattccaac
gagcagtttgttagttactagttctcgaaataactgaatatctaattgtcttgcctggtt
aactgcatgggtggggtaagcctagaagtatgagaccgaagcctggtaagaagggaaaat
tttaatctccccccccccttatctcgacgcggacctctcggtttggggccaatattcatc
cgcaaaattacgttcgtacttagcaatgcaacacggggtaaactacttccactattgcta
gtacacatactattcccttacccattgcgggatcccactccattccaataaaaactgttc
aacaagcgagtcggtagcaaaaaatgacactttcgtgaatggaggtagagtcccattcta
tacatttaatgaaatgaaaaatggcggcgcaagttgcagtaggacgaaaatccgttggtt
tcacaggaccgtgagggttcgactccctctatccccaacgagacacttcaaataacctat
ttcaggttgtttggattcacacaacttgttcggaagcaaaatacggaagccacttcaatt
tttttcctgcctttggtctttcaaaaacactttgcaattgagccattcaggcttttcata
tacatgaatggctcaattgagccccccccccccctctagactttatttactggaaccaat
attgtattaaacaggtcgataaaggcgagatcgacggtttgactaggctcc-aaaaaaat
ggagttgaaaaatatactcaacggattttcagttgagttttatccgtaaatgcattag--
-----------------
