>Tapeinidium_biserratum_Wade4305_KTHU1951_01_r2_1.000_abundance_41
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------taagtgatagatagacatatctattgctctttctcgtt
attactagtttgtatctgtattaccctctttccttattccaaaactattagttaatagta
ttaactattatataggagtattaagatattgcgatgaatacctctaaataaaccaacctg
tggcatataagaaatatatatcgtgaatgaagatagagtcctattctacatagttgctga
aagctgcgacgcaagttgcggtggaaagaaaatccgttggttttacacgaccg-------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Odontosoria_alutacea
ctaggatcatttagcgggcaatcctgagccaaatctcacttcgaatagaattcggacgat
aaatagagataggtacagagactctacgggggttattctaacaaacaactaattagttgc
cattccgtgaagatctaaatagttagatcttttatatgactggctgttaaatacggggta
aaccccaggaatatgagacgattacataataaaatagatcaaatgatagttttttacgaa
attcggaagtcgcccccccttttgttatgccgccgaaaataacaatcaaaccgattcctc
ctatatggcatagtactagaagtaagtgatagataggtatacctagcgccgtttctgatt
attgctagtttgtatctgtatttccctctcttcttatt-------------------ata
taatttgttctctaggaatatcggaatatt-caacgaatgctagttactaaattagctag
tgacatataagaaggatatgttgtgaatgaagatagagtcctattctacatagttactga
aagctgtgacgcaagttgcggtggaaagaaaatccgttggttttaaacagccgtgagggt
tcgagtccctctatccccaacgagacacttcagctcatgctgttcccgctcacaagattt
gtctttctcttccgaaagaagagattgtagaacctccttgtccgactcgaagtttcccca
aatcgatcaatttagagaaatgcgccgattcctcggaaaacattacataacacaaccctc
tccttacttctatttaaaaagaaagtaagacgttttaaaagtatctaatcggtcggtttg
gagaagaagtcgaccgattagatactttgatttgacacccacctgtgagtataggtagtc
ataaatatgtaaagacatctatcaatagagagacattcaaatttatctctttttttccgc
tataaaaagcttgaaacgaagaacgaaggcagtactcaaaacttgaatctcttttcaatg
gagtgttttgaataaacaaattggccgggatagctcagttggtagagcagaggactgaaa
