>Tapeinidium_biserratum_Wade4305_KTHU1951_01_r1_1.000_abundance_40
-----------------------------------tctcctcgaatagaattcggccagt
aaatagagataggtacagagactctacgggggttattctaacgaacaactaattagttcc
cagttccacaaatatctaaaaagatagttagttattgtgtatgacaggcagttatatata
cacagggtaaagtccagaggtctgaaacaattacacaataaaagaaaagagatcaaatga
tagtttagtttttcacgagattcgggagtagccctcttttatgttat---accaaagatc
aaaatcaagc--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------
>Odontosoria_alutacea
ctaggatcatttagcgggcaatcctgagccaaatctcacttcgaatagaattcggacgat
aaatagagataggtacagagactctacgggggttattctaacaaacaactaattagttgc
ca-ttccgtgaagatctaa----atagttagatcttttatatgactggctgttaaat---
-acggggtaaaccccaggaatatgagacgattacataat-----aaaatagatcaaatga
-----tagttttttacgaaattcggaagtcgcccccccttttgttatgccgccgaaaata
acaatcaaaccgattcctcctatatggcatagtactagaagtaagtgatagataggtata
cctagcgccgtttctgattattgctagtttgtatctgtatttccctctcttcttattata
taatttgttctctaggaatatcggaatattcaacgaatgctagttactaaattagctagt
gacatataagaaggatatgttgtgaatgaagatagagtcctattctacatagttactgaa
agctgtgacgcaagttgcggtggaaagaaaatccgttggttttaaacagccgtgagggtt
cgagtccctctatccccaacgagacacttcagctcatgctgttcccgctcacaagatttg
tctttctcttccgaaagaagagattgtagaacctccttgtccgactcgaagtttccccaa
atcgatcaatttagagaaatgcgccgattcctcggaaaacattacataacacaaccctct
ccttacttctatttaaaaagaaagtaagacgttttaaaagtatctaatcggtcggtttgg
agaagaagtcgaccgattagatactttgatttgacacccacctgtgagtataggtagtca
taaatatgtaaagacatctatcaatagagagacattcaaatttatctctttttttccgct
ataaaaagcttgaaacgaagaacgaaggcagtactcaaaacttgaatctcttttcaatgg
agtgttttgaataaacaaattggccgggatagctcagttggtagagcagaggactgaaa
