---
R1FastqGz: /PowerBarcoder/data/amplicon_data/trim_RUN1.5_R1.fq.gz
R2FastqGz: /PowerBarcoder/data/amplicon_data/trim_RUN1.5_R2.fq.gz
amplicon_r1:
- rbcLN_amplicon_r1.fq
amplicon_r2:
- rbcLN_amplicon_r2.fq
barcodesFile1:
- barcodes_rbcL_start_0.fasta
barcodesFile2:
- barcodes_rbcLN_start2_0.fasta
customizedCoreNumber:
- '30'
dada2BarcodeFile: multiplex_cpDNAbarcode_clean.txt
dada2LearnErrorFile: /PowerBarcoder/data/dada2LearnErrorFile/
errorRateCutadaptor:
- '0.125'
minimumLengthCutadaptor:
- '70'
minimumLengthCutadaptorInLoop:
- '150'
nameOfLoci:
- rbcLN
primerF:
- GAGACTAAAGCAGGTGTTGGATTCA
primerR:
- TCAAGTCCACCRCGAAGRCATTC
sseqidFileName:
- fermalies_rbcL.fasta
