---
R1FastqGz: RUN1-5_R1.fastq.gz
R2FastqGz: RUN1-5_R2.fastq.gz
ampliconInfo: /PowerBarcoder/data/amplicon_data/
barcodesFile1:
- barcodes_rbcL_start_0.fasta
barcodesFile2:
- barcodes_rbcLN_start2_0.fasta
customizedCoreNumber:
- '30'
dada2BarcodeFile: multiplex_cpDNAbarcode_clean.txt
dada2LearnErrorFile: /PowerBarcoder/data/dada2LearnErrorFile/
errorRateCutadaptor:
- '0.125'
minimumLengthCutadaptor:
- '70'
minimumLengthCutadaptorInLoop:
- '150'
nameOfLoci:
- rbcLN
primerF:
- GAGACTAAAGCAGGTGTTGGATTCA
primerR:
- TCAAGTCCACCRCGAAGRCATTC
sseqidFileName:
- fermalies_rbcL.fasta
