---
R1FastqGz: RUN1-5_R1.fastq.gz
R2FastqGz: RUN1-5_R2.fastq.gz
ampliconInfo: /PowerBarcoder/data/amplicon_data/
barcodesFile1:
- barcodes_rbcL_start_0.fasta
barcodesFile2:
- barcodes_rbcLN_start2_0.fasta
blastParsingMode:
- '2'
blastReadChoosingMode:
- '1'
customizedCoreNumber:
- '30'
dada2BarcodeFile: multiplex_cpDNAbarcode_clean.txt
dada2LearnErrorFile: /PowerBarcoder/data/dada2LearnErrorFile/
dev_mode: '1'
errorRateCutadapt:
- '0.125'
maximum_mismatch_base_pair:
- '0'
minimumLengthCutadapt:
- '70'
minimumLengthCutadaptInLoop:
- '150'
minimum_overlap_base_pair:
- '12'
nameOfLoci:
- rbcLN
primerF:
- GAGACTAAAGCAGGTGTTGGATTCA
primerFName:
- fVGF
primerR:
- TCAAGTCCACCRCGAAGRCATTC
primerRName:
- rECL
sseqidFileName:
- fermalies_rbcL.fasta
